// Security scan rules — cross-language patterns for secrets, injection,
// cryptography, and access control vulnerabilities.

import type { ScanRule } from './types'
import { JS_TS, PY, JAVA } from './constants'

export const SECURITY_RULES: ScanRule[] = [

  // ---------------------------------------------------------------------------
  // Secrets & Credentials
  // ---------------------------------------------------------------------------

  {
    id: 'hardcoded-aws-key',
    category: 'security',
    severity: 'critical',
    title: 'Hardcoded AWS Key',
    description: 'AWS access key ID found in source code. If committed, this grants access to your AWS account. Rotate the key immediately and use environment variables or IAM roles.',
    suggestion: 'Move to environment variable: process.env.AWS_ACCESS_KEY_ID or use IAM roles',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '(?:AKIA|ASIA)[A-Z0-9]{16}',
    patternOptions: { regex: true, caseSensitive: true },
    confidence: 'high',
  },
  {
    id: 'hardcoded-secret',
    category: 'security',
    severity: 'critical',
    title: 'Potential Hardcoded Secret',
    description: 'A value resembling an API key, token, or secret is assigned directly in code. Secrets in source code can be extracted from version history even after deletion.',
    suggestion: 'Move to environment variables or a secrets manager (Vault, AWS SSM, etc.)',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '(?:api[_-]?key|api[_-]?secret|secret[_-]?key|access[_-]?token|auth[_-]?token|private[_-]?key|client[_-]?secret|\\bsecret\\b)\\s*[:=]\\s*["\'][^"\']{8,}["\']',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|ENV\[|example|placeholder|your[_-]|xxx|changeme|TODO|test[_-]|fake[_-]|mock[_-]|sample[_-]|dummy|fixture|\.md["']|README|schema|zod|yup|type\b|interface\b|label|i18n|locale|translation|field|\bform\b|\binput\b|\bdisplay\b|message|dataclass|@dataclass/i,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite|\.test\.|_test\.\w+$|\.spec\.|__tests__|[/\\]tests?[/\\]|fixture|e2e|docker-compose|\.ya?ml$|\.toml$|\.env\.example|\.env\.template|\.env\.sample/i,
    confidence: 'medium',
    fix: "process.env.API_KEY",
    fixDescription: 'Move to environment variable or secrets manager (Vault, AWS SSM)',
  },
  {
    id: 'hardcoded-password',
    category: 'security',
    severity: 'critical',
    title: 'Hardcoded Password',
    description: 'Password string found hardcoded in source. Attackers who gain source access immediately have credentials.',
    suggestion: 'Never store passwords in code. Use environment variables, a secrets manager, or prompt at runtime.',
    cwe: 'CWE-259',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/259.html',
    pattern: '(?:password|passwd|pwd)\\s*[:=]\\s*["\'][^"\']{4,}["\']',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|placeholder|example|your[_-]|xxx|changeme|schema|zod|yup|validate|type\b|interface\b|Props|param|arg|hash|bcrypt|scrypt|label|i18n|locale|translation|field|\bform\b|\binput\b|\bdisplay\b|message|dataclass|@dataclass/i,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite|\.test\.|_test\.\w+$|\.spec\.|__tests__|[/\\]tests?[/\\]|fixture|e2e|docker-compose|\.ya?ml$|\.toml$|\.env\.example|\.env\.template|\.env\.sample/i,
    confidence: 'medium',
    fix: "process.env.DB_PASSWORD",
    fixDescription: 'Move to environment variable or secrets manager',
  },
  {
    id: 'private-key-inline',
    category: 'security',
    severity: 'critical',
    title: 'Private Key in Source',
    description: 'An SSH, PGP, or RSA private key marker was found in source code. Private keys must never be committed.',
    suggestion: 'Move to a file outside the repo, use a secrets manager, or mount at deploy time',
    cwe: 'CWE-321',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/321.html',
    pattern: '-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /example|test|mock|fixture|sample/i,
    confidence: 'high',
  },
  {
    id: 'github-token',
    category: 'security',
    severity: 'critical',
    title: 'GitHub Token in Source',
    description: 'A GitHub personal access token, OAuth token, or app token was found in code.',
    suggestion: 'Rotate the token immediately and use GITHUB_TOKEN env var',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    pattern: '(?:ghp_[A-Za-z0-9_]{36}|gho_[A-Za-z0-9_]{36}|ghu_[A-Za-z0-9_]{36}|ghs_[A-Za-z0-9_]{36}|github_pat_[A-Za-z0-9_]{22}_[A-Za-z0-9]{59})',
    patternOptions: { regex: true, caseSensitive: true },
    confidence: 'high',
  },

  // ---------------------------------------------------------------------------
  // Injection
  // ---------------------------------------------------------------------------

  {
    id: 'eval-usage',
    category: 'security',
    severity: 'critical',
    title: 'eval() / new Function() Usage',
    description: 'eval() and new Function() execute arbitrary strings as code. If user input reaches these, it enables Remote Code Execution (RCE).',
    suggestion: 'Use JSON.parse() for data, or a sandboxed interpreter. Refactor to avoid dynamic code execution.',
    cwe: 'CWE-94',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/94.html',
    pattern: '\\b(?:eval|new\\s+Function)\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /\/\/.*eval|\/\*.*eval|\*.*eval|eslint|no-eval|JSON\.parse/,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite|\.d\.ts$|\.test\.|\.spec\.|__tests__|fixture|mock/i,
    confidence: 'high',
    fix: 'JSON.parse(data)',
    fixDescription: 'Use JSON.parse() for data parsing, or Function constructor for controlled dynamic evaluation',
  },
  {
    id: 'innerhtml-xss',
    category: 'security',
    severity: 'warning',
    title: 'innerHTML / dangerouslySetInnerHTML',
    description: 'Direct HTML injection creates Cross-Site Scripting (XSS) vulnerabilities if the content includes unsanitized user input. Attackers can steal session tokens and perform actions as the user.',
    suggestion: 'Sanitize with DOMPurify before injection, or use textContent/innerText for plain text',
    cwe: 'CWE-79',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/79.html',
    pattern: '(?:\\.innerHTML\\s*=|dangerouslySetInnerHTML)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /DOMPurify|sanitize|purify|escape|xss|shiki|prism|highlight|highlighter|marked|markdown|rehype/i,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    confidence: 'medium',
    fix: 'element.textContent = value',
    fixDescription: 'Use textContent for plain text, or DOMPurify.sanitize(html) for HTML content',
  },
  {
    id: 'sql-injection',
    category: 'security',
    severity: 'critical',
    title: 'Potential SQL Injection',
    description: 'String interpolation or concatenation in an SQL query. If user input flows into this, attackers can read, modify, or delete your entire database.',
    suggestion: 'Use parameterized queries ($1, ?) or an ORM. Never concatenate user input into SQL.',
    cwe: 'CWE-89',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/89.html',
    pattern: '(?:query|execute|prepare|raw|exec)\\s*\\(\\s*[`"\']\\s*(?:SELECT|INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE).*(?:\\$\\{|\\+\\s*["\']|\\+\\s*\\w)',
    patternOptions: { regex: true, caseSensitive: false },
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    confidence: 'high',
    fix: "db.query('SELECT * FROM users WHERE id = $1', [userId])",
    fixDescription: 'Use parameterized queries or prepared statements with placeholders',
  },
  {
    id: 'command-injection-template',
    category: 'security',
    severity: 'critical',
    title: 'Command Injection via Template Literal',
    description: 'Shell command built with template literal string interpolation. If user input reaches this, attackers can execute arbitrary OS commands on the server.',
    suggestion: 'Use execFile() or spawn() with an argument array instead of exec(). Never pass user input through a shell.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: '(?:child_process\\.exec|execSync|exec)\\s*\\(\\s*`',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    confidence: 'high',
  },
  {
    id: 'command-injection-exec-direct',
    category: 'security',
    severity: 'critical',
    title: 'child_process.exec() Direct Call',
    description: 'child_process.exec() runs commands through a shell (/bin/sh), which parses metacharacters like ;, |, &&, $(), and backticks. If ANY part of the command string is constructed from external input (user data, filenames, URLs), an attacker can inject additional commands. Unlike execFile(), exec() always invokes a shell.',
    suggestion: 'Replace exec() with execFile() or spawn() using an array of arguments: execFile("cmd", ["arg1", "arg2"]). This bypasses the shell entirely, preventing injection.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: 'child_process\\.exec(?:Sync)?\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /execFile|\/\/.*exec|test|mock/i,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    confidence: 'high',
  },
  {
    id: 'command-injection-require-cp',
    category: 'security',
    severity: 'warning',
    title: 'child_process Imported',
    description: 'This file imports the child_process module which enables OS command execution. Files using child_process require careful review to ensure no user input flows into commands. The exec() function is particularly dangerous as it invokes a shell.',
    suggestion: 'Prefer execFile() over exec(). Validate and sanitize all inputs. Consider if child_process is truly necessary.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: '(?:require\\s*\\(\\s*[\'"]child_process[\'"]\\)|from\\s+[\'"]child_process[\'"]|from\\s+[\'"]node:child_process[\'"])',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'medium',
  },
  {
    id: 'command-injection-string-concat',
    category: 'security',
    severity: 'warning',
    title: 'Shell Command Built with String Concatenation',
    description: 'A variable named "command" or "cmd" is built using string concatenation (+). If this string is later passed to exec() or similar, any concatenated user input enables command injection.',
    suggestion: 'Use execFile() with argument arrays instead of building command strings',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: '(?:command|cmd)\\s*(?:=|\\+=)\\s*(?:[\'"`].*\\+|.*\\+\\s*[\'"`])',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /\/\/|sql|query|css|class|style/i,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    confidence: 'medium',
  },
  {
    id: 'command-injection-util-format',
    category: 'security',
    severity: 'critical',
    title: 'Shell Command Built via util.format()',
    description: 'util.format() is used to construct strings that may be passed to shell execution. This is a classic command injection pattern: the format string builds a shell command with user-controlled values interpolated via %s/%d. An attacker can inject shell metacharacters (;, |, &&, $()) in the interpolated values to execute arbitrary commands.',
    suggestion: 'Use execFile() with an argument array instead. If you must build command strings, use shell-escape or shell-quote to sanitize interpolated values.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: 'util\\.format\\s*\\(\\s*[\'"][^\'"]*(?:convert|identify|gs|pdftk|ffmpeg|imagemagick|graphicsmagick|wkhtmlto|phantomjs|cmd|exec|bash|sh |rm |mv |cp |cat |chmod|chown|mkdir|curl|wget)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'path-traversal',
    category: 'security',
    severity: 'warning',
    title: 'Potential Path Traversal',
    description: 'File path constructed with string concatenation or template literals. If user input is included, attackers can read files outside the intended directory (e.g., /etc/passwd).',
    suggestion: 'Use path.resolve() with a base directory and validate the result stays within bounds. Use path.join() and check with startsWith().',
    cwe: 'CWE-22',
    owasp: 'A01:2021 Broken Access Control',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/22.html',
    pattern: '(?:readFile|writeFile|readdir|createReadStream|createWriteStream|open|access)(?:Sync)?\\s*\\(\\s*(?:`[^`]*\\$\\{|[^,]+\\+)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /path\.resolve|path\.join.*startsWith|__dirname|__filename|process\.cwd/,
    confidence: 'medium',
  },
  {
    id: 'open-redirect',
    category: 'security',
    severity: 'warning',
    title: 'Potential Open Redirect',
    description: 'Redirect destination may come from user input. Open redirects let attackers craft links that redirect victims to phishing sites while appearing to originate from your domain.',
    suggestion: 'Validate redirect URLs against an allowlist of trusted domains. Never redirect to arbitrary user-supplied URLs.',
    cwe: 'CWE-601',
    owasp: 'A01:2021 Broken Access Control',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/601.html',
    pattern: '(?:redirect|location\\.href|window\\.location|res\\.redirect)\\s*(?:=|\\()\\s*(?:req\\.|params\\.|query\\.|searchParams)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // Cryptography
  // ---------------------------------------------------------------------------

  {
    id: 'weak-hash',
    category: 'security',
    severity: 'warning',
    title: 'Weak Hash Algorithm (MD5/SHA1)',
    description: 'MD5 and SHA1 are cryptographically broken and must not be used for passwords, signatures, or integrity checks. Collisions can be practically computed.',
    suggestion: 'Use SHA-256+ for integrity, bcrypt/scrypt/argon2 for passwords',
    cwe: 'CWE-328',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/328.html',
    pattern: '(?:createHash|hashlib|MessageDigest\\.getInstance|Digest::)\\s*\\(?\\s*["\'](?:md5|sha1|sha-1)["\']',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /checksum|etag|cache|fingerprint|\.test\.|\.spec\./i,
    confidence: 'medium',
  },
  {
    id: 'insecure-random',
    category: 'security',
    severity: 'warning',
    title: 'Insecure Random Number Generator',
    description: 'Math.random() is not cryptographically secure. If used for tokens, session IDs, or security-sensitive values, the output is predictable.',
    suggestion: 'Use crypto.randomUUID(), crypto.getRandomValues(), or crypto.randomBytes() for security-sensitive values',
    cwe: 'CWE-338',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/338.html',
    pattern: 'Math\\.random\\(\\).*(?:token|session|secret|key|password|nonce|salt|csrf|id)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // Access Control
  // ---------------------------------------------------------------------------

  {
    id: 'cors-wildcard',
    category: 'security',
    severity: 'warning',
    title: 'CORS Wildcard Origin',
    description: 'Access-Control-Allow-Origin: * permits any website to make requests to your API. Combined with credentials, this exposes authenticated endpoints to any origin.',
    suggestion: 'Restrict to specific trusted origins. If credentials are used, wildcard is already rejected by browsers.',
    cwe: 'CWE-942',
    owasp: 'A01:2021 Broken Access Control',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/942.html',
    pattern: 'Access-Control-Allow-Origin["\']?\\s*[:,]\\s*["\']\\*["\']',
    patternOptions: { regex: true },
    excludePattern: /development|dev\.config|NODE_ENV.*development|process\.env/i,
    confidence: 'medium',
  },
  {
    id: 'jwt-no-verify',
    category: 'security',
    severity: 'critical',
    title: 'JWT Decoded Without Verification',
    description: 'jwt.decode() reads the payload without verifying the signature. Attackers can forge tokens with arbitrary claims. Always use jwt.verify().',
    suggestion: 'Replace jwt.decode() with jwt.verify(token, secret) to validate the signature',
    cwe: 'CWE-347',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/347.html',
    pattern: '\\bjwt\\.decode\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: [...JS_TS, ...PY],
    confidence: 'medium',
  },
  // ---------------------------------------------------------------------------
  // Secrets & Credentials — LLM / SaaS API Keys
  // ---------------------------------------------------------------------------

  {
    id: 'llm-openai-key',
    category: 'security',
    severity: 'critical',
    title: 'OpenAI API Key in Source',
    description: 'An OpenAI API key (sk-…) was found in source code. These keys grant access to paid API resources and should never be committed.',
    suggestion: 'Move to environment variable: process.env.OPENAI_API_KEY or use a secrets manager',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: 'sk-[A-Za-z0-9]{20,}',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|your[_-]|xxx|changeme|test[_-]|fake[_-]|mock[_-]|sample[_-]|sk-[a-z]{4}\.{3}|sk-\.{3}/i,
    confidence: 'high',
  },
  {
    id: 'llm-anthropic-key',
    category: 'security',
    severity: 'critical',
    title: 'Anthropic API Key in Source',
    description: 'An Anthropic API key (sk-ant-…) was found in source code. Rotate immediately and use environment variables.',
    suggestion: 'Move to environment variable: process.env.ANTHROPIC_API_KEY or use a secrets manager',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: 'sk-ant-[A-Za-z0-9-]{20,}',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]|sample[_-]/i,
    confidence: 'high',
  },
  {
    id: 'llm-google-ai-key',
    category: 'security',
    severity: 'critical',
    title: 'Google AI / Gemini API Key in Source',
    description: 'A Google AI API key (AIzaSy…) was found in source code. These keys can be used to access Google Cloud APIs.',
    suggestion: 'Move to environment variable or use Google Cloud service account credentials',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: 'AIzaSy[A-Za-z0-9_-]{33}',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'high',
  },
  {
    id: 'slack-token',
    category: 'security',
    severity: 'critical',
    title: 'Slack Token in Source',
    description: 'A Slack bot, user, or app token was found in source code. Slack tokens can be used to read messages, post as the bot, and access workspace data.',
    suggestion: 'Rotate the token immediately and use SLACK_TOKEN environment variable',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: 'xox[bpras]-[A-Za-z0-9-]{10,}',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'high',
  },
  {
    id: 'stripe-key',
    category: 'security',
    severity: 'critical',
    title: 'Stripe Secret Key in Source',
    description: 'A Stripe live secret key (sk_live_…) was found in source code. This key can be used to make charges, issue refunds, and access customer data.',
    suggestion: 'Rotate the key immediately and use STRIPE_SECRET_KEY environment variable',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: 'sk_live_[A-Za-z0-9]{20,}',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'high',
  },

  // ---------------------------------------------------------------------------
  // Prototype Pollution
  // ---------------------------------------------------------------------------

  {
    id: 'prototype-pollution-assign',
    category: 'security',
    severity: 'warning',
    title: 'Prototype Pollution via Object.assign()',
    description: 'Object.assign() with a user-controlled source (req.body, req.query, etc.) can inject __proto__ or constructor properties, polluting the Object prototype for all objects in the process.',
    suggestion: 'Validate/sanitize input before merging. Use a safe-merge library or strip __proto__ keys.',
    cwe: 'CWE-1321',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1321.html',
    pattern: 'Object\\.assign\\s*\\(\\s*(?:req\\.|params\\.|query\\.|body\\.|input\\.|data\\.|user\\.)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'medium',
  },
  {
    id: 'prototype-pollution-merge',
    category: 'security',
    severity: 'warning',
    title: 'Prototype Pollution via Deep Merge',
    description: 'Deep merge utilities (_.merge, lodash.merge, deepmerge) recursively assign properties without checking __proto__. If the source is user-controlled, prototype pollution is possible.',
    suggestion: 'Use a merge function that skips __proto__ and constructor keys, or validate input first.',
    cwe: 'CWE-1321',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1321.html',
    pattern: '(?:_\\.(?:merge|defaultsDeep)|lodash\\.merge|deepmerge|deep-extend)\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /safeMerge|sanitize|strip.*proto/i,
    confidence: 'low',
  },
  {
    id: 'prototype-pollution-proto',
    category: 'security',
    severity: 'warning',
    title: 'Direct __proto__ Access',
    description: 'Direct access to __proto__ can be used to modify the Object prototype. If the key comes from user input, this enables prototype pollution attacks.',
    suggestion: 'Use Object.create(null) for dictionaries or validate that keys are not __proto__ or constructor.',
    cwe: 'CWE-1321',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1321.html',
    pattern: '__proto__\\s*[=\\[]|\\[\\s*[\'"]__proto__[\'"]\\s*\\]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /hasOwnProperty|Object\.create\(null\)|sanitize|test|spec|mock/i,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // JWT Vulnerabilities
  // ---------------------------------------------------------------------------

  {
    id: 'jwt-algo-none',
    category: 'security',
    severity: 'critical',
    title: 'JWT Algorithm "none" Allowed',
    description: 'Allowing the "none" algorithm in JWT verification disables signature checking entirely. Attackers can forge tokens with arbitrary claims.',
    suggestion: 'Always specify a strong algorithm (RS256, ES256, HS256) and never allow "none".',
    cwe: 'CWE-347',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/347.html',
    pattern: 'algorithms?\\s*[:=]\\s*.*[\'"]none[\'"]',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: [...JS_TS, ...PY],
    confidence: 'high',
  },
  {
    id: 'jwt-weak-secret',
    category: 'security',
    severity: 'warning',
    title: 'JWT Signed with Short/Weak Secret',
    description: 'JWT signed with a secret shorter than 16 characters. Short secrets are vulnerable to brute-force attacks.',
    suggestion: 'Use a secret of at least 32 characters, or use asymmetric keys (RS256/ES256). Store secrets in environment variables.',
    cwe: 'CWE-326',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/326.html',
    pattern: 'jwt\\.sign\\s*\\([^,]+,\\s*[\'"][^\'"]{1,15}[\'"]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /test|spec|mock|fixture|example|process\.env|env\./i,
    confidence: 'medium',
  },
  {
    id: 'jwt-missing-algorithms',
    category: 'security',
    severity: 'warning',
    title: 'JWT Verify Without Specifying Algorithms',
    description: 'jwt.verify() called without an explicit algorithms array. Without algorithm restriction, an attacker may exploit algorithm confusion (e.g., switching RS256 to HS256).',
    suggestion: 'Always pass { algorithms: ["RS256"] } (or your chosen algorithm) as an option to jwt.verify().',
    cwe: 'CWE-347',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/347.html',
    pattern: 'jwt\\.verify\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /algorithms/,
    confidence: 'low',
  },

  // ---------------------------------------------------------------------------
  // Cookie Security
  // ---------------------------------------------------------------------------

  {
    id: 'cookie-no-httponly',
    category: 'security',
    severity: 'warning',
    title: 'Cookie Without httpOnly Flag',
    description: 'Setting httpOnly to false allows JavaScript to access the cookie via document.cookie, enabling cookie theft through XSS attacks.',
    suggestion: 'Set httpOnly: true for all session and authentication cookies.',
    cwe: 'CWE-1004',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1004.html',
    pattern: 'httpOnly\\s*:\\s*false',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'cookie-no-secure',
    category: 'security',
    severity: 'warning',
    title: 'Cookie Without secure Flag',
    description: 'Setting secure to false allows the cookie to be sent over unencrypted HTTP, exposing it to network sniffing attacks.',
    suggestion: 'Set secure: true for all cookies, especially session/auth cookies.',
    cwe: 'CWE-614',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/614.html',
    pattern: 'secure\\s*:\\s*false',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludePattern: /localhost|development|test|isDev/i,
    confidence: 'high',
  },
  {
    id: 'cookie-no-samesite',
    category: 'security',
    severity: 'info',
    title: 'Cookie Without sameSite Attribute',
    description: 'Cookies without the sameSite attribute are sent on cross-site requests by default, enabling CSRF attacks.',
    suggestion: 'Set sameSite: "strict" or sameSite: "lax" on all cookies.',
    cwe: 'CWE-1275',
    owasp: 'A01:2021 Broken Access Control',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1275.html',
    pattern: 'res\\.cookie\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /sameSite/i,
    confidence: 'low',
  },

  // ---------------------------------------------------------------------------
  // Information Exposure
  // ---------------------------------------------------------------------------

  {
    id: 'error-stack-exposure',
    category: 'security',
    severity: 'warning',
    title: 'Stack Trace Sent to Client',
    description: 'Stack traces sent in HTTP responses reveal internal file paths, framework versions, and code structure to attackers.',
    suggestion: 'Log stack traces server-side only. Return a generic error message to clients.',
    cwe: 'CWE-209',
    owasp: 'A04:2021 Insecure Design',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/209.html',
    pattern: '(?:res|response)\\.(?:json|send|status)\\s*\\([^)]*(?:err\\.stack|error\\.stack|\\.stack)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'verbose-error-response',
    category: 'security',
    severity: 'info',
    title: 'Full Error Object Sent to Client',
    description: 'Sending the raw error object in an HTTP response may expose internal details such as stack traces, database queries, or server paths.',
    suggestion: 'Map errors to safe response objects: { message: "Something went wrong", code: "INTERNAL_ERROR" }.',
    cwe: 'CWE-209',
    owasp: 'A04:2021 Insecure Design',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/209.html',
    pattern: '(?:res|response)\\.(?:json|send)\\s*\\(\\s*(?:err|error)\\s*\\)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /errorHandler|errorMiddleware|test|spec|mock/i,
    confidence: 'medium',
  },
  {
    id: 'debug-mode-production',
    category: 'security',
    severity: 'info',
    title: 'Debug Mode Possibly Enabled',
    description: 'Debug flags left enabled can expose verbose diagnostics, stack traces, and internal state to attackers.',
    suggestion: 'Ensure debug mode is disabled in production. Use environment-based configuration.',
    cwe: 'CWE-489',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/489.html',
    pattern: '(?:DEBUG|debug)\\s*[:=]\\s*(?:true|1|[\'"]true[\'"])',
    patternOptions: { regex: true },
    excludePattern: /env\.development|env\.test|env\.local|process\.env|import\.meta\.env|NODE_ENV|test|spec|__test__|fixture/i,
    excludeFiles: /\.env\.development|\.env\.test|\.env\.local|test|spec|fixture/i,
    confidence: 'low',
  },
  {
    id: 'console-log-sensitive',
    category: 'security',
    severity: 'warning',
    title: 'Sensitive Data in Console Log',
    description: 'Logging sensitive data (passwords, secrets, tokens, API keys) can expose credentials in log files, CI output, or monitoring systems.',
    suggestion: 'Remove sensitive data from log statements or mask values before logging.',
    cwe: 'CWE-532',
    owasp: 'A09:2021 Security Logging and Monitoring Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/532.html',
    pattern: 'console\\.(?:log|warn|error|info|debug)\\s*\\([^)]*(?:password|secret|apiKey|api_key|credential|ssn|credit.?card)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludePattern: /test|spec|mock|fixture|\*.*password|schema|validate|type\b|label|i18n|locale|translation|field|form|input|display|message/i,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // GraphQL
  // ---------------------------------------------------------------------------

  {
    id: 'graphql-introspection-enabled',
    category: 'security',
    severity: 'warning',
    title: 'GraphQL Introspection Enabled',
    description: 'GraphQL introspection allows anyone to query the full API schema, revealing all types, fields, and mutations. This should be disabled in production.',
    suggestion: 'Disable introspection in production: introspection: process.env.NODE_ENV !== "production"',
    cwe: 'CWE-200',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/200.html',
    pattern: 'introspection\\s*:\\s*true',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /development|test|NODE_ENV|process\.env/i,
    confidence: 'medium',
  },
  {
    id: 'graphql-no-depth-limit',
    category: 'security',
    severity: 'warning',
    title: 'GraphQL Server Without Depth Limiting',
    description: 'GraphQL servers without query depth limiting are vulnerable to deeply nested query attacks that exhaust server resources.',
    suggestion: 'Add graphql-depth-limit or a similar plugin: validationRules: [depthLimit(10)]',
    cwe: 'CWE-400',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/400.html',
    pattern: '(?:ApolloServer|graphqlHTTP|createYoga|makeExecutableSchema)\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /depthLimit|depth-limit|maxDepth|queryComplexity/i,
    confidence: 'low',
  },

  // ---------------------------------------------------------------------------
  // Timing Attacks
  // ---------------------------------------------------------------------------

  {
    id: 'timing-attack-comparison',
    category: 'security',
    severity: 'warning',
    title: 'Non-Constant-Time Secret Comparison',
    description: 'Comparing secrets with === allows timing attacks. The comparison short-circuits on the first mismatched character, leaking information about the secret one byte at a time.',
    suggestion: 'Use crypto.timingSafeEqual() or a constant-time comparison library.',
    cwe: 'CWE-208',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/208.html',
    pattern: '(?:===?\\s*(?:secret|password|token|apiKey|api_key|hash)|(?:secret|password|token|apiKey|api_key|hash)\\s*===?)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludePattern: /timingSafeEqual|constantTimeCompare|safeCompare|constant.?time|test|spec|mock|type\b|interface\b|\bconfirm\s*\(|validation|Props|Component|render|React/i,
    confidence: 'low',
  },
  {
    id: 'timing-attack-py',
    category: 'security',
    severity: 'warning',
    title: 'Non-Constant-Time Secret Comparison (Python)',
    description: 'Comparing secrets with == in Python allows timing attacks. Use hmac.compare_digest() for constant-time comparisons.',
    suggestion: 'Use hmac.compare_digest(a, b) instead of a == b for secret comparisons.',
    cwe: 'CWE-208',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/208.html',
    pattern: '(?:==\\s*(?:secret|password|token|api_key|hash)|(?:secret|password|token|api_key|hash)\\s*==)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: PY,
    excludePattern: /compare_digest|constant.?time|test|spec|mock/i,
    confidence: 'low',
  },

  // ---------------------------------------------------------------------------
  // ReDoS (Regular Expression Denial of Service)
  // ---------------------------------------------------------------------------

  {
    id: 'redos-user-regex',
    category: 'security',
    severity: 'warning',
    title: 'User Input in RegExp Constructor',
    description: 'Constructing a RegExp from user input (req.body, req.query, etc.) enables Regular Expression Denial of Service (ReDoS). Malicious patterns with catastrophic backtracking can hang the event loop.',
    suggestion: 'Validate/sanitize input, use a safe regex library (re2), or avoid building RegExp from user input entirely.',
    cwe: 'CWE-1333',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1333.html',
    pattern: 'new\\s+RegExp\\s*\\(\\s*(?:req\\.|params\\.|query\\.|body\\.|input\\.|user\\.|args\\.)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'redos-dynamic-regex',
    category: 'security',
    severity: 'info',
    title: 'Dynamic RegExp from Variable',
    description: 'RegExp constructed from a variable (not a literal string). If the variable originates from user input, this may enable ReDoS attacks.',
    suggestion: 'Prefer regex literals. If dynamic regex is needed, validate the pattern and use the re2 library.',
    cwe: 'CWE-1333',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1333.html',
    pattern: 'new\\s+RegExp\\s*\\(\\s*[a-zA-Z_$]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /escaped|sanitize|re2|safe|literal|test|spec|mock/i,
    confidence: 'low',
  },

  // ---------------------------------------------------------------------------
  // XXE (XML External Entity)
  // ---------------------------------------------------------------------------

  {
    id: 'xxe-js-parser',
    category: 'security',
    severity: 'warning',
    title: 'XML Parser Without Entity Restriction (JS)',
    description: 'XML parsers (DOMParser, xml2js, fast-xml-parser, libxmljs) may process external entities by default, enabling XXE attacks that read local files or make server-side requests.',
    suggestion: 'Disable external entity processing. For xml2js, no action needed (safe by default). For libxmljs, set noent: false.',
    cwe: 'CWE-611',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/611.html',
    pattern: '(?:DOMParser|xml2js|fast-xml-parser|libxmljs)\\s*[\\.(]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /noent\s*:\s*false|resolveEntities\s*:\s*false|test|spec|mock/i,
    confidence: 'low',
  },
  {
    id: 'xxe-python',
    category: 'security',
    severity: 'warning',
    title: 'Unsafe XML Parser (Python)',
    description: 'Python\'s built-in XML parsers (xml.etree, xml.dom.minidom, xml.sax) are vulnerable to XXE attacks. Use defusedxml instead.',
    suggestion: 'Use defusedxml.ElementTree instead of xml.etree.ElementTree. Install: pip install defusedxml.',
    cwe: 'CWE-611',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/611.html',
    pattern: '(?:xml\\.etree\\.ElementTree|xml\\.dom\\.minidom|xml\\.sax)\\.parse',
    patternOptions: { regex: true },
    fileFilter: PY,
    excludePattern: /defusedxml|defused/i,
    confidence: 'medium',
  },
  {
    id: 'xxe-java',
    category: 'security',
    severity: 'warning',
    title: 'Unsafe XML Parser Factory (Java)',
    description: 'Java XML parser factories (DocumentBuilderFactory, SAXParserFactory, XMLInputFactory) process external entities by default. Configure secure processing features.',
    suggestion: 'Call factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true) before creating the parser.',
    cwe: 'CWE-611',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/611.html',
    pattern: '(?:DocumentBuilderFactory|SAXParserFactory|XMLInputFactory)\\.newInstance',
    patternOptions: { regex: true },
    fileFilter: JAVA,
    excludePattern: /setFeature.*disallow-doctype-decl|FEATURE_SECURE_PROCESSING/i,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // Log Injection
  // ---------------------------------------------------------------------------

  {
    id: 'log-injection-js',
    category: 'security',
    severity: 'info',
    title: 'User Input in Log Statement (JS)',
    description: 'Logging unsanitized user input (req.body, req.query, etc.) enables log injection. Attackers can inject fake log entries, newlines, or ANSI escape codes to corrupt log analysis.',
    suggestion: 'Sanitize user input before logging: strip newlines and control characters.',
    cwe: 'CWE-117',
    owasp: 'A09:2021 Security Logging and Monitoring Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/117.html',
    pattern: '(?:console\\.(?:log|warn|error|info)|logger\\.(?:log|warn|error|info|debug))\\s*\\([^)]*(?:req\\.|params\\.|query\\.|body\\.|input\\.|user\\.)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /sanitize|escape|strip|clean|test|spec|mock/i,
    confidence: 'low',
  },
  {
    id: 'log-injection-py',
    category: 'security',
    severity: 'info',
    title: 'User Input in Log Statement (Python)',
    description: 'Logging unsanitized user input (request.form, request.args, etc.) enables log injection. Attackers can inject fake log entries to mislead forensic analysis.',
    suggestion: 'Sanitize user input before logging or use structured logging with explicit field extraction.',
    cwe: 'CWE-117',
    owasp: 'A09:2021 Security Logging and Monitoring Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/117.html',
    pattern: '(?:logging\\.(?:info|warning|error|debug|critical)|logger\\.(?:info|warning|error|debug|critical))\\s*\\([^)]*(?:request\\.|form\\.|args\\.)',
    patternOptions: { regex: true },
    fileFilter: PY,
    excludePattern: /sanitize|escape|strip|clean|test|spec|mock/i,
    confidence: 'low',
  },

  // ---------------------------------------------------------------------------
  // Weak Cryptography — Ciphers & Modes
  // ---------------------------------------------------------------------------

  {
    id: 'weak-cipher-des',
    category: 'security',
    severity: 'warning',
    title: 'Weak Cipher: DES / 3DES',
    description: 'DES has a 56-bit key (brute-forceable in hours) and 3DES is deprecated by NIST since 2023. Both are considered insecure for new applications.',
    suggestion: 'Use AES-256-GCM or ChaCha20-Poly1305 for symmetric encryption.',
    cwe: 'CWE-327',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/327.html',
    pattern: '(?:DES(?:ede)?|3DES|TripleDES|DESede)',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /\/\/|\/\*|\*|#|comment|doc|readme|\.md|describe|test|spec/i,
    confidence: 'medium',
  },
  {
    id: 'weak-cipher-rc4',
    category: 'security',
    severity: 'warning',
    title: 'Weak Cipher: RC4',
    description: 'RC4 has known biases and is prohibited by RFC 7465 for TLS. It must not be used for any purpose.',
    suggestion: 'Use AES-256-GCM or ChaCha20-Poly1305 instead.',
    cwe: 'CWE-327',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/327.html',
    pattern: '(?:RC4|ARC4|ARCFOUR)',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /\/\/|\/\*|\*|#|comment|doc|readme|\.md|describe|test|spec/i,
    confidence: 'medium',
  },
  {
    id: 'weak-cipher-ecb',
    category: 'security',
    severity: 'warning',
    title: 'Weak Cipher Mode: ECB',
    description: 'ECB (Electronic Codebook) mode encrypts identical plaintext blocks to identical ciphertext blocks, revealing patterns in the data. It is never appropriate for encrypting data longer than one block.',
    suggestion: 'Use CBC with a random IV, or preferably authenticated encryption (GCM, CCM).',
    cwe: 'CWE-327',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/327.html',
    pattern: '(?:ECB|\\.MODE_ECB|AES\\/ECB|[\'"]ecb[\'"])',
    patternOptions: { regex: true },
    excludePattern: /\/\/|\/\*|\*|#|comment|doc|readme|\.md|describe|test|spec/i,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // SSTI (Server-Side Template Injection)
  // ---------------------------------------------------------------------------

  {
    id: 'ssti-js',
    category: 'security',
    severity: 'critical',
    title: 'Server-Side Template Injection (JS)',
    description: 'Passing user input directly to template engine render/compile functions (ejs, pug, handlebars) can allow attackers to execute arbitrary code on the server.',
    suggestion: 'Never pass user input as the template source. Use pre-compiled templates and pass user input as data context only.',
    cwe: 'CWE-1336',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1336.html',
    pattern: '(?:ejs|pug|hbs|handlebars|nunjucks|mustache)\\.(?:render|compile|renderFile)\\s*\\([^)]*(?:req\\.|params\\.|query\\.|body\\.|input\\.|user\\.)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'ssti-python',
    category: 'security',
    severity: 'critical',
    title: 'Server-Side Template Injection (Python)',
    description: 'render_template_string() or Template() with user input enables Server-Side Template Injection. Attackers can execute arbitrary Python code via Jinja2 template expressions.',
    suggestion: 'Use render_template() with a file path instead of render_template_string(). Never pass user input as the template source.',
    cwe: 'CWE-1336',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1336.html',
    pattern: '(?:render_template_string|Template)\\s*\\(\\s*(?:request\\.|form\\.|args\\.|.*\\+)',
    patternOptions: { regex: true },
    fileFilter: PY,
    confidence: 'high',
  },

  // ---------------------------------------------------------------------------
  // TLS/SSL Misconfiguration
  // ---------------------------------------------------------------------------

  {
    id: 'tls-reject-unauthorized-false',
    category: 'security',
    severity: 'critical',
    title: 'TLS Certificate Verification Disabled',
    description: 'Setting rejectUnauthorized to false disables TLS certificate verification, allowing man-in-the-middle attacks. Any certificate — expired, self-signed, or attacker-controlled — will be accepted.',
    suggestion: 'Remove rejectUnauthorized: false. Use properly signed certificates. For development, use mkcert to create local CA-signed certs.',
    cwe: 'CWE-295',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/295.html',
    pattern: 'rejectUnauthorized\\s*[:=]\\s*false',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /test|spec|mock|fixture|development|localhost/i,
    confidence: 'high',
  },
  {
    id: 'tls-env-disable',
    category: 'security',
    severity: 'critical',
    title: 'TLS Verification Globally Disabled via Environment',
    description: 'Setting NODE_TLS_REJECT_UNAUTHORIZED=0 disables TLS certificate verification for ALL HTTPS requests in the entire Node.js process. This is a severe security risk.',
    suggestion: 'Remove this setting entirely. Fix the underlying certificate issue instead. Use properly signed certificates or configure a custom CA.',
    cwe: 'CWE-295',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/295.html',
    pattern: 'NODE_TLS_REJECT_UNAUTHORIZED\\s*=\\s*[\'"]?0[\'"]?',
    patternOptions: { regex: true },
    excludePattern: /test|spec|mock|fixture|#.*NODE_TLS/i,
    confidence: 'high',
  },

  // ---------------------------------------------------------------------------
  // Hardcoded Crypto Parameters
  // ---------------------------------------------------------------------------

  {
    id: 'hardcoded-iv',
    category: 'security',
    severity: 'critical',
    title: 'Hardcoded Initialization Vector (IV)',
    description: 'A hardcoded IV in createCipheriv defeats the purpose of the IV, which must be unique and unpredictable for each encryption operation. Reusing IVs enables plaintext recovery attacks.',
    suggestion: 'Generate a random IV for each encryption: crypto.randomBytes(16). Prepend the IV to the ciphertext for decryption.',
    cwe: 'CWE-329',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/329.html',
    pattern: 'createCipheriv\\s*\\([^,]+,\\s*[^,]+,\\s*(?:[\'"]|Buffer\\.from\\s*\\(\\s*[\'"])',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /randomBytes|generateKey|test|spec|mock/i,
    confidence: 'high',
  },
  {
    id: 'hardcoded-salt',
    category: 'security',
    severity: 'warning',
    title: 'Hardcoded Salt Value',
    description: 'A hardcoded salt in a key derivation function (pbkdf2, bcrypt) makes rainbow table attacks feasible. Each password must use a unique, random salt.',
    suggestion: 'Generate a random salt per password: crypto.randomBytes(16). Store the salt alongside the hash.',
    cwe: 'CWE-760',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/760.html',
    pattern: '(?:pbkdf2|bcrypt\\.\\w+)\\s*\\([^,]+,\\s*[\'"]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /randomBytes|generateSalt|test|spec|mock/i,
    confidence: 'medium',
  },
  {
    id: 'static-crypto-key',
    category: 'security',
    severity: 'critical',
    title: 'Hardcoded Encryption Key',
    description: 'A string literal is used as an encryption key in createCipher/createCipheriv. Hardcoded keys can be extracted from source code and used to decrypt all data.',
    suggestion: 'Use environment variables or a key management service (AWS KMS, HashiCorp Vault) for encryption keys.',
    cwe: 'CWE-321',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/321.html',
    pattern: 'createCipher(?:iv)?\\s*\\([^,]+,\\s*[\'"]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /process\.env|env\.|randomBytes|test|spec|mock/i,
    confidence: 'high',
  },
  {
    id: 'hardcoded-hmac-key',
    category: 'security',
    severity: 'warning',
    title: 'Hardcoded HMAC Secret',
    description: 'A string literal is used as an HMAC secret in createHmac. Hardcoded secrets can be extracted from source code and used to forge message authentication codes.',
    suggestion: 'Store HMAC secrets in environment variables or a secrets manager.',
    cwe: 'CWE-321',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/321.html',
    pattern: 'createHmac\\s*\\([^,]+,\\s*[\'"]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /process\.env|env\.|test|spec|mock/i,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // Node.js Sandbox Escapes
  // ---------------------------------------------------------------------------

  {
    id: 'vm-code-execution',
    category: 'security',
    severity: 'critical',
    title: 'Node.js vm Module Code Execution',
    description: 'The Node.js vm module does NOT provide a secure sandbox. Code running in vm contexts can escape to the host process and access the full Node.js API.',
    suggestion: 'Use isolated-vm or a separate process/container for untrusted code execution. Never rely on vm for security.',
    cwe: 'CWE-94',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/94.html',
    pattern: '\\bvm\\.(?:runInNewContext|runInThisContext|createScript|compileFunction)\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'vm2-deprecated',
    category: 'security',
    severity: 'warning',
    title: 'vm2 Module (Deprecated — Known Sandbox Escapes)',
    description: 'vm2 is deprecated due to multiple known sandbox escape vulnerabilities (CVE-2023-29199, CVE-2023-30547). It cannot safely sandbox untrusted code.',
    suggestion: 'Migrate to isolated-vm, or run untrusted code in a separate container or process.',
    cwe: 'CWE-94',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://github.com/nicedayfor/vm2/issues/533',
    pattern: '(?:require\\s*\\(\\s*[\'"]vm2[\'"]\\)|from\\s+[\'"]vm2[\'"])',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'worker-eval',
    category: 'security',
    severity: 'warning',
    title: 'Worker Thread with eval Enabled',
    description: 'Creating a Worker with eval: true allows arbitrary code execution within the worker thread. If the code source is user-controlled, this enables RCE.',
    suggestion: 'Use a file-based Worker instead of eval mode. If dynamic code is needed, validate and sandbox the input.',
    cwe: 'CWE-94',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/94.html',
    pattern: 'new\\s+Worker\\s*\\([^)]*eval\\s*:\\s*true',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // Object Injection
  // ---------------------------------------------------------------------------

  {
    id: 'object-injection-bracket',
    category: 'security',
    severity: 'warning',
    title: 'Dynamic Property Access with Request Data',
    description: 'Using request data (req.body, req.query, req.params) as a computed property key enables object injection. Attackers can access or overwrite unexpected properties including __proto__.',
    suggestion: 'Validate the property key against an allowlist of expected values, or use a Map instead of a plain object.',
    cwe: 'CWE-1321',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/1321.html',
    pattern: '\\w+\\[req\\.(?:body|query|params)\\.\\w+\\]',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /allowlist|whitelist|validKeys|allowedKeys|test|spec|mock/i,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // Insecure Deserialization
  // ---------------------------------------------------------------------------

  {
    id: 'node-serialize-unserialize',
    category: 'security',
    severity: 'critical',
    title: 'node-serialize — Known RCE Vulnerability',
    description: 'The node-serialize package is known to allow Remote Code Execution via its unserialize() function. Crafted payloads can execute arbitrary code during deserialization.',
    suggestion: 'Remove node-serialize entirely. Use JSON.parse() for data interchange. If complex serialization is needed, use a safe alternative.',
    cwe: 'CWE-502',
    owasp: 'A08:2021 Software and Data Integrity Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/502.html',
    pattern: '(?:require\\s*\\(\\s*[\'"]node-serialize[\'"]\\)|\\.unserialize\\s*\\()',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    confidence: 'high',
  },
  {
    id: 'serialize-javascript-exec',
    category: 'security',
    severity: 'warning',
    title: 'Serialized Data Passed to eval()',
    description: 'Using serialize-javascript output with eval() reconstructs executable code from serialized data, enabling code injection if the serialized content is attacker-controlled.',
    suggestion: 'Use JSON.parse() instead of eval() for deserialization. If serialize-javascript is needed, never eval the output from untrusted sources.',
    cwe: 'CWE-502',
    owasp: 'A08:2021 Software and Data Integrity Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/502.html',
    pattern: 'serialize-javascript',
    patternOptions: { regex: false },
    fileFilter: JS_TS,
    excludePattern: /test|spec|mock|README|\.md/i,
    confidence: 'low',
  },

  // ---------------------------------------------------------------------------
  // Secret Detection — Additional Providers
  // ---------------------------------------------------------------------------

  {
    id: 'twilio-token',
    category: 'security',
    severity: 'warning',
    title: 'Twilio API Key in Source',
    description: 'A Twilio API key (SK…) was found in source code. Twilio keys can be used to send SMS, make calls, and access account resources.',
    suggestion: 'Rotate the key immediately and use TWILIO_API_KEY environment variable.',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '\\bSK[a-f0-9]{32}\\b',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'medium',
  },
  {
    id: 'sendgrid-key',
    category: 'security',
    severity: 'critical',
    title: 'SendGrid API Key in Source',
    description: 'A SendGrid API key (SG.…) was found in source code. This key can be used to send emails on your behalf.',
    suggestion: 'Rotate the key immediately and use SENDGRID_API_KEY environment variable.',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '\\bSG\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9_-]{43}\\b',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'high',
  },
  {
    id: 'npm-token',
    category: 'security',
    severity: 'critical',
    title: 'npm Token in Source',
    description: 'An npm automation or publish token (npm_…) was found in source code. This token can be used to publish packages to the npm registry under your account.',
    suggestion: 'Rotate the token immediately at npmjs.com and use NPM_TOKEN environment variable.',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '\\bnpm_[A-Za-z0-9]{36}\\b',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'high',
  },
  {
    id: 'pypi-token',
    category: 'security',
    severity: 'critical',
    title: 'PyPI Token in Source',
    description: 'A PyPI API token (pypi-…) was found in source code. This token can be used to publish packages to PyPI under your account.',
    suggestion: 'Rotate the token immediately at pypi.org and use PYPI_TOKEN environment variable.',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '\\bpypi-[A-Za-z0-9_-]{100,}\\b',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'high',
  },
  {
    id: 'azure-connection-string',
    category: 'security',
    severity: 'critical',
    title: 'Azure Connection String in Source',
    description: 'An Azure Storage or Service Bus connection string with an embedded AccountKey was found in source code. This grants full access to the Azure resource.',
    suggestion: 'Rotate the key immediately and use AZURE_STORAGE_CONNECTION_STRING environment variable or Azure Managed Identity.',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: 'DefaultEndpointsProtocol=.*AccountKey=[A-Za-z0-9+/=]{20,}',
    patternOptions: { regex: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'high',
  },
  {
    id: 'heroku-api-key',
    category: 'security',
    severity: 'warning',
    title: 'Heroku API Key in Source',
    description: 'A Heroku API key was found in source code. This key can be used to manage Heroku apps, databases, and deployments.',
    suggestion: 'Rotate the key immediately and use HEROKU_API_KEY environment variable.',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '[hH]eroku.*[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
    patternOptions: { regex: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'medium',
  },
  {
    id: 'mailgun-key',
    category: 'security',
    severity: 'warning',
    title: 'Mailgun API Key in Source',
    description: 'A Mailgun API key (key-…) was found in source code. This key can be used to send emails and manage domains.',
    suggestion: 'Rotate the key immediately and use MAILGUN_API_KEY environment variable.',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '\\bkey-[A-Za-z0-9]{32}\\b',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|example|placeholder|test[_-]|fake[_-]|mock[_-]/i,
    confidence: 'medium',
  },

  // ---------------------------------------------------------------------------
  // CSP Misconfigurations
  // ---------------------------------------------------------------------------

  {
    id: 'csp-unsafe-inline',
    category: 'security',
    severity: 'warning',
    title: 'CSP Contains unsafe-inline',
    description: 'Content-Security-Policy with \'unsafe-inline\' allows inline scripts and styles, defeating XSS protection. Attackers can inject inline <script> tags that the browser will execute.',
    suggestion: 'Use nonce-based or hash-based CSP instead of unsafe-inline. Refactor inline scripts to external files.',
    cwe: 'CWE-693',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/693.html',
    pattern: 'Content-Security-Policy.*unsafe-inline',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /\/\/|#|comment|report-only|test|spec|mock/i,
    confidence: 'medium',
  },
  {
    id: 'csp-unsafe-eval',
    category: 'security',
    severity: 'warning',
    title: 'CSP Contains unsafe-eval',
    description: 'Content-Security-Policy with \'unsafe-eval\' allows eval(), new Function(), and similar dynamic code execution, undermining XSS protections.',
    suggestion: 'Remove unsafe-eval from CSP. Refactor code to avoid eval() and new Function().',
    cwe: 'CWE-693',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/693.html',
    pattern: 'Content-Security-Policy.*unsafe-eval',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /\/\/|#|comment|report-only|test|spec|mock/i,
    confidence: 'medium',
  },
  {
    id: 'csp-wildcard-source',
    category: 'security',
    severity: 'warning',
    title: 'CSP Contains Wildcard Source',
    description: 'Content-Security-Policy with * as a source allows loading resources from any domain, defeating the purpose of CSP.',
    suggestion: 'Replace wildcard with specific trusted domains. Use self for same-origin resources.',
    cwe: 'CWE-693',
    owasp: 'A05:2021 Security Misconfiguration',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/693.html',
    pattern: 'Content-Security-Policy[^;]*(?:script-src|style-src|default-src|img-src|connect-src|font-src|frame-src)\\s[^;]*\\*',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /\/\/|#|comment|report-only|test|spec|mock/i,
    confidence: 'medium',
  },
  // --- NoSQL Injection ---
  {
    id: 'nosql-injection',
    category: 'security',
    severity: 'critical',
    title: 'Potential NoSQL Injection',
    description: 'MongoDB operators like $where, $regex, $gt, $ne constructed from user input can allow attackers to bypass authentication or extract data.',
    suggestion: 'Validate and sanitize all user input before using in MongoDB queries. Use parameterized queries or a MongoDB ODM like Mongoose with schema validation.',
    cwe: 'CWE-943',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/943.html',
    pattern: '\\$(?:where|regex|gt|gte|lt|lte|ne|in|nin|or|and|not|nor|exists|elemMatch)\\s*[:\\]}].*(?:req\\.|params\\.|query\\.|body\\.|request\\.|input|userInput|user_input)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    excludePattern: /schema|validate|sanitize|mock|test|fixture|example/i,
    confidence: 'high',
  },
  {
    id: 'nosql-injection-mapreduce',
    category: 'security',
    severity: 'critical',
    title: 'NoSQL Injection via mapReduce',
    description: 'MongoDB mapReduce with user-controlled functions can execute arbitrary server-side JavaScript.',
    suggestion: 'Avoid mapReduce with user input. Use aggregation pipeline instead, which does not execute arbitrary JavaScript.',
    cwe: 'CWE-943',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/943.html',
    pattern: 'mapReduce\\s*\\(.*(?:req\\.|params\\.|query\\.|body\\.|request\\.|input|userInput)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    confidence: 'high',
  },
  // --- Prompt Injection ---
  {
    id: 'prompt-injection',
    category: 'security',
    severity: 'warning',
    title: 'Potential Prompt Injection',
    description: 'User input concatenated directly into LLM prompt strings can allow prompt injection attacks, potentially causing the model to ignore instructions or leak data.',
    suggestion: 'Separate system prompts from user input. Use the model\'s user message role for user input instead of concatenating into system prompts. Apply input validation and output filtering.',
    cwe: 'CWE-77',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/77.html',
    pattern: '(?:system|prompt|instruction|context)\\s*(?:=|:)\\s*`[^`]*\\$\\{(?:req\\.|params\\.|query\\.|body\\.|request\\.|input|userInput|user_input|message|content)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    excludePattern: /sanitize|escape|validate|example|mock|test|fixture/i,
    confidence: 'medium',
  },
  // --- Deprecated TLS ---
  {
    id: 'deprecated-tls',
    category: 'security',
    severity: 'warning',
    title: 'Deprecated TLS/SSL Version',
    description: 'TLS 1.0, TLS 1.1, and SSLv3 are deprecated and have known vulnerabilities. Modern applications should use TLS 1.2 or TLS 1.3.',
    suggestion: 'Update TLS configuration to require TLS 1.2 or higher. Set minVersion to TLSv1.2 or TLSv1.3.',
    cwe: 'CWE-327',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/327.html',
    pattern: 'TLSv1[^.2-9]|TLSv1_method|TLSv1_1|TLSv1\\.0|TLSv1\\.1|SSLv3|SSLv2|secureProtocol.*(?:TLSv1_method|TLSv1_1_method|SSLv3_method)|minVersion.*(?:TLSv1(?!\\.[2-9])|TLSv1_1)',
    patternOptions: { regex: true },
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    excludePattern: /\/\/|comment|deprecated|history|changelog|README|docs|migration/i,
    confidence: 'high',
  },
  // --- localStorage/sessionStorage Secrets ---
  {
    id: 'localstorage-secret',
    category: 'security',
    severity: 'warning',
    title: 'Secret Stored in Browser Storage',
    description: 'Storing tokens, passwords, or API keys in localStorage/sessionStorage exposes them to XSS attacks. Any script on the page can read these values.',
    suggestion: 'Use httpOnly secure cookies for authentication tokens. For temporary client-side secrets, consider in-memory storage with short expiration.',
    cwe: 'CWE-922',
    owasp: 'A04:2021 Insecure Design',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/922.html',
    pattern: '(?:localStorage|sessionStorage)\\.setItem\\s*\\(\\s*[\'"][^\'"]*(?:token|secret|password|api[_-]?key|auth|credential|private[_-]?key|access[_-]?key|client[_-]?secret)[^\'"]*[\'"]',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite/i,
    excludePattern: /test|mock|fixture|example|theme|preference|locale|language/i,
    confidence: 'medium',
  },

  // -----------------------------------------------------------------------
  // Sensitive Data in URL (CWE-598)
  // -----------------------------------------------------------------------

  {
    id: 'sensitive-data-in-url',
    category: 'security',
    severity: 'warning',
    title: 'Sensitive Data in URL: Query Parameter Exposure',
    description:
      'A URL with sensitive data (password, token, secret, API key) as a query parameter was detected. Query parameters are logged in server access logs, browser history, referrer headers, and proxy logs, exposing credentials to unauthorized parties.',
    suggestion:
      'Send sensitive data in request headers (Authorization header) or POST body instead of URL query parameters.',
    cwe: 'CWE-598',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/598.html',
    pattern: '\\?(.*&)?(password|token|secret|key|api_key|apikey|auth)=',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
    excludeFiles: /rules-security|rules-security-lang|rules-quality|rules-framework|rules-composite|test|fixture|__tests__|e2e|spec/i,
    excludePattern: /example|mock|test|fixture|placeholder|TODO/i,
    confidence: 'medium',
  },
]
