// Security scan rules — cross-language patterns for secrets, injection,
// cryptography, and access control vulnerabilities.

import type { ScanRule } from './types'
import { JS_TS, PY } from './constants'

export const SECURITY_RULES: ScanRule[] = [

  // ---------------------------------------------------------------------------
  // Secrets & Credentials
  // ---------------------------------------------------------------------------

  {
    id: 'hardcoded-aws-key',
    category: 'security',
    severity: 'critical',
    title: 'Hardcoded AWS Key',
    description: 'AWS access key ID found in source code. If committed, this grants access to your AWS account. Rotate the key immediately and use environment variables or IAM roles.',
    suggestion: 'Move to environment variable: process.env.AWS_ACCESS_KEY_ID or use IAM roles',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '(?:AKIA|ASIA)[A-Z0-9]{16}',
    patternOptions: { regex: true, caseSensitive: true },
  },
  {
    id: 'hardcoded-secret',
    category: 'security',
    severity: 'critical',
    title: 'Potential Hardcoded Secret',
    description: 'A value resembling an API key, token, or secret is assigned directly in code. Secrets in source code can be extracted from version history even after deletion.',
    suggestion: 'Move to environment variables or a secrets manager (Vault, AWS SSM, etc.)',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/798.html',
    pattern: '(?:api[_-]?key|api[_-]?secret|secret[_-]?key|access[_-]?token|auth[_-]?token|private[_-]?key|client[_-]?secret)\\s*[:=]\\s*["\'][^"\']{8,}["\']',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|ENV\[|example|placeholder|your[_-]|xxx|changeme|TODO|test[_-]|fake[_-]|mock[_-]|sample[_-]|dummy|fixture|\.md["']|README|schema|zod|yup|type\b|interface\b/i,
  },
  {
    id: 'hardcoded-password',
    category: 'security',
    severity: 'critical',
    title: 'Hardcoded Password',
    description: 'Password string found hardcoded in source. Attackers who gain source access immediately have credentials.',
    suggestion: 'Never store passwords in code. Use environment variables, a secrets manager, or prompt at runtime.',
    cwe: 'CWE-259',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/259.html',
    pattern: '(?:password|passwd|pwd)\\s*[:=]\\s*["\'][^"\']{4,}["\']',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /process\.env|import\.meta\.env|env\.|getenv|os\.environ|placeholder|example|your[_-]|xxx|changeme|schema|zod|yup|validate|type\b|interface\b|Props|param|arg|hash|bcrypt|scrypt/i,
  },
  {
    id: 'private-key-inline',
    category: 'security',
    severity: 'critical',
    title: 'Private Key in Source',
    description: 'An SSH, PGP, or RSA private key marker was found in source code. Private keys must never be committed.',
    suggestion: 'Move to a file outside the repo, use a secrets manager, or mount at deploy time',
    cwe: 'CWE-321',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/321.html',
    pattern: '-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----',
    patternOptions: { regex: true, caseSensitive: true },
    excludePattern: /example|test|mock|fixture|sample/i,
  },
  {
    id: 'github-token',
    category: 'security',
    severity: 'critical',
    title: 'GitHub Token in Source',
    description: 'A GitHub personal access token, OAuth token, or app token was found in code.',
    suggestion: 'Rotate the token immediately and use GITHUB_TOKEN env var',
    cwe: 'CWE-798',
    owasp: 'A07:2021 Identification and Authentication Failures',
    pattern: '(?:ghp_[A-Za-z0-9_]{36}|gho_[A-Za-z0-9_]{36}|ghu_[A-Za-z0-9_]{36}|ghs_[A-Za-z0-9_]{36}|github_pat_[A-Za-z0-9_]{22}_[A-Za-z0-9]{59})',
    patternOptions: { regex: true, caseSensitive: true },
  },

  // ---------------------------------------------------------------------------
  // Injection
  // ---------------------------------------------------------------------------

  {
    id: 'eval-usage',
    category: 'security',
    severity: 'critical',
    title: 'eval() / new Function() Usage',
    description: 'eval() and new Function() execute arbitrary strings as code. If user input reaches these, it enables Remote Code Execution (RCE).',
    suggestion: 'Use JSON.parse() for data, or a sandboxed interpreter. Refactor to avoid dynamic code execution.',
    cwe: 'CWE-94',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/94.html',
    pattern: '\\b(?:eval|new\\s+Function)\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /\/\/.*eval|\/\*.*eval|\*.*eval|eslint|no-eval|JSON\.parse/,
  },
  {
    id: 'innerhtml-xss',
    category: 'security',
    severity: 'warning',
    title: 'innerHTML / dangerouslySetInnerHTML',
    description: 'Direct HTML injection creates Cross-Site Scripting (XSS) vulnerabilities if the content includes unsanitized user input. Attackers can steal session tokens and perform actions as the user.',
    suggestion: 'Sanitize with DOMPurify before injection, or use textContent/innerText for plain text',
    cwe: 'CWE-79',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/79.html',
    pattern: '(?:\\.innerHTML\\s*=|dangerouslySetInnerHTML)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /DOMPurify|sanitize|purify|escape|xss/i,
  },
  {
    id: 'sql-injection',
    category: 'security',
    severity: 'critical',
    title: 'Potential SQL Injection',
    description: 'String interpolation or concatenation in an SQL query. If user input flows into this, attackers can read, modify, or delete your entire database.',
    suggestion: 'Use parameterized queries ($1, ?) or an ORM. Never concatenate user input into SQL.',
    cwe: 'CWE-89',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/89.html',
    pattern: '(?:query|execute|prepare|raw|exec)\\s*\\(\\s*[`"\']\\s*(?:SELECT|INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE).*(?:\\$\\{|\\+\\s*["\']|\\+\\s*\\w)',
    patternOptions: { regex: true, caseSensitive: false },
  },
  {
    id: 'command-injection-template',
    category: 'security',
    severity: 'critical',
    title: 'Command Injection via Template Literal',
    description: 'Shell command built with template literal string interpolation. If user input reaches this, attackers can execute arbitrary OS commands on the server.',
    suggestion: 'Use execFile() or spawn() with an argument array instead of exec(). Never pass user input through a shell.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: '(?:child_process\\.exec|execSync|exec)\\s*\\(\\s*`',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
  },
  {
    id: 'command-injection-exec-direct',
    category: 'security',
    severity: 'critical',
    title: 'child_process.exec() Direct Call',
    description: 'child_process.exec() runs commands through a shell (/bin/sh), which parses metacharacters like ;, |, &&, $(), and backticks. If ANY part of the command string is constructed from external input (user data, filenames, URLs), an attacker can inject additional commands. Unlike execFile(), exec() always invokes a shell.',
    suggestion: 'Replace exec() with execFile() or spawn() using an array of arguments: execFile("cmd", ["arg1", "arg2"]). This bypasses the shell entirely, preventing injection.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: 'child_process\\.exec(?:Sync)?\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /execFile|\/\/.*exec|test|mock/i,
  },
  {
    id: 'command-injection-require-cp',
    category: 'security',
    severity: 'warning',
    title: 'child_process Imported',
    description: 'This file imports the child_process module which enables OS command execution. Files using child_process require careful review to ensure no user input flows into commands. The exec() function is particularly dangerous as it invokes a shell.',
    suggestion: 'Prefer execFile() over exec(). Validate and sanitize all inputs. Consider if child_process is truly necessary.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: '(?:require\\s*\\(\\s*[\'"]child_process[\'"]\\)|from\\s+[\'"]child_process[\'"]|from\\s+[\'"]node:child_process[\'"])',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
  },
  {
    id: 'command-injection-string-concat',
    category: 'security',
    severity: 'warning',
    title: 'Shell Command Built with String Concatenation',
    description: 'A variable named "command" or "cmd" is built using string concatenation (+). If this string is later passed to exec() or similar, any concatenated user input enables command injection.',
    suggestion: 'Use execFile() with argument arrays instead of building command strings',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: '(?:command|cmd)\\s*(?:=|\\+=)\\s*(?:[\'"`].*\\+|.*\\+\\s*[\'"`])',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /\/\/|sql|query|css|class|style/i,
  },
  {
    id: 'command-injection-util-format',
    category: 'security',
    severity: 'critical',
    title: 'Shell Command Built via util.format()',
    description: 'util.format() is used to construct strings that may be passed to shell execution. This is a classic command injection pattern: the format string builds a shell command with user-controlled values interpolated via %s/%d. An attacker can inject shell metacharacters (;, |, &&, $()) in the interpolated values to execute arbitrary commands.',
    suggestion: 'Use execFile() with an argument array instead. If you must build command strings, use shell-escape or shell-quote to sanitize interpolated values.',
    cwe: 'CWE-78',
    owasp: 'A03:2021 Injection',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/78.html',
    pattern: 'util\\.format\\s*\\(\\s*[\'"][^\'"]*(?:convert|identify|gs|pdftk|ffmpeg|imagemagick|graphicsmagick|wkhtmlto|phantomjs|cmd|exec|bash|sh |rm |mv |cp |cat |chmod|chown|mkdir|curl|wget)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
  },
  {
    id: 'path-traversal',
    category: 'security',
    severity: 'warning',
    title: 'Potential Path Traversal',
    description: 'File path constructed with string concatenation or template literals. If user input is included, attackers can read files outside the intended directory (e.g., /etc/passwd).',
    suggestion: 'Use path.resolve() with a base directory and validate the result stays within bounds. Use path.join() and check with startsWith().',
    cwe: 'CWE-22',
    owasp: 'A01:2021 Broken Access Control',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/22.html',
    pattern: '(?:readFile|writeFile|readdir|createReadStream|createWriteStream|open|access)(?:Sync)?\\s*\\(\\s*(?:`[^`]*\\$\\{|[^,]+\\+)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
    excludePattern: /path\.resolve|path\.join.*startsWith|__dirname|__filename|process\.cwd/,
  },
  {
    id: 'open-redirect',
    category: 'security',
    severity: 'warning',
    title: 'Potential Open Redirect',
    description: 'Redirect destination may come from user input. Open redirects let attackers craft links that redirect victims to phishing sites while appearing to originate from your domain.',
    suggestion: 'Validate redirect URLs against an allowlist of trusted domains. Never redirect to arbitrary user-supplied URLs.',
    cwe: 'CWE-601',
    owasp: 'A01:2021 Broken Access Control',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/601.html',
    pattern: '(?:redirect|location\\.href|window\\.location|res\\.redirect)\\s*(?:=|\\()\\s*(?:req\\.|params\\.|query\\.|searchParams)',
    patternOptions: { regex: true },
    fileFilter: JS_TS,
  },

  // ---------------------------------------------------------------------------
  // Cryptography
  // ---------------------------------------------------------------------------

  {
    id: 'weak-hash',
    category: 'security',
    severity: 'warning',
    title: 'Weak Hash Algorithm (MD5/SHA1)',
    description: 'MD5 and SHA1 are cryptographically broken and must not be used for passwords, signatures, or integrity checks. Collisions can be practically computed.',
    suggestion: 'Use SHA-256+ for integrity, bcrypt/scrypt/argon2 for passwords',
    cwe: 'CWE-328',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/328.html',
    pattern: '(?:createHash|hashlib|MessageDigest\\.getInstance|Digest::)\\s*\\(?\\s*["\'](?:md5|sha1|sha-1)["\']',
    patternOptions: { regex: true, caseSensitive: false },
    excludePattern: /checksum|etag|cache|fingerprint|\.test\.|\.spec\./i,
  },
  {
    id: 'insecure-random',
    category: 'security',
    severity: 'warning',
    title: 'Insecure Random Number Generator',
    description: 'Math.random() is not cryptographically secure. If used for tokens, session IDs, or security-sensitive values, the output is predictable.',
    suggestion: 'Use crypto.randomUUID(), crypto.getRandomValues(), or crypto.randomBytes() for security-sensitive values',
    cwe: 'CWE-338',
    owasp: 'A02:2021 Cryptographic Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/338.html',
    pattern: 'Math\\.random\\(\\).*(?:token|session|secret|key|password|nonce|salt|csrf|id)',
    patternOptions: { regex: true, caseSensitive: false },
    fileFilter: JS_TS,
  },

  // ---------------------------------------------------------------------------
  // Access Control
  // ---------------------------------------------------------------------------

  {
    id: 'cors-wildcard',
    category: 'security',
    severity: 'warning',
    title: 'CORS Wildcard Origin',
    description: 'Access-Control-Allow-Origin: * permits any website to make requests to your API. Combined with credentials, this exposes authenticated endpoints to any origin.',
    suggestion: 'Restrict to specific trusted origins. If credentials are used, wildcard is already rejected by browsers.',
    cwe: 'CWE-942',
    owasp: 'A01:2021 Broken Access Control',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/942.html',
    pattern: 'Access-Control-Allow-Origin["\']?\\s*[:,]\\s*["\']\\*["\']',
    patternOptions: { regex: true },
  },
  {
    id: 'jwt-no-verify',
    category: 'security',
    severity: 'critical',
    title: 'JWT Decoded Without Verification',
    description: 'jwt.decode() reads the payload without verifying the signature. Attackers can forge tokens with arbitrary claims. Always use jwt.verify().',
    suggestion: 'Replace jwt.decode() with jwt.verify(token, secret) to validate the signature',
    cwe: 'CWE-347',
    owasp: 'A07:2021 Identification and Authentication Failures',
    learnMoreUrl: 'https://cwe.mitre.org/data/definitions/347.html',
    pattern: '\\bjwt\\.decode\\s*\\(',
    patternOptions: { regex: true },
    fileFilter: [...JS_TS, ...PY],
  },
]
