/**
 * Markdown export — generate a human-readable Markdown report from analysis data.
 */

import type { FullAnalysis } from '@/lib/code/import-parser'
import type { ScanResults, CodeIssue } from '@/lib/code/issue-scanner'
import type { CodeIndex } from '@/lib/code/code-index'
import type { GitHubRepo } from '@/types/repository'
import type { ProjectSummary } from '@/lib/diagrams/types'
import { coverageNotice } from '@/lib/repository'

// ---------------------------------------------------------------------------
// Full Markdown report
// ---------------------------------------------------------------------------

/**
 * Generate a comprehensive Markdown report covering the project summary,
 * issues, and dependency information.
 */
export function exportToMarkdown(
  repo: GitHubRepo,
  codeIndex: CodeIndex,
  analysis: FullAnalysis | null,
  scanResults: ScanResults | null,
  summary: ProjectSummary | null,
): string {
  const lines: string[] = []

  lines.push(`# ${repo.fullName} — Analysis Report`)
  lines.push('')
  lines.push(`> Generated by [RepoLens](${repo.url}) on ${new Date().toLocaleDateString()}`)
  lines.push('')
  const notice = coverageNotice(codeIndex.coverage)
  if (notice) lines.push(`> **Coverage notice:** ${notice}`, '')

  // Repo metadata
  lines.push('## Repository')
  lines.push('')
  lines.push(`| Property | Value |`)
  lines.push(`| --- | --- |`)
  lines.push(`| URL | ${repo.url} |`)
  lines.push(`| Default branch | \`${repo.defaultBranch}\` |`)
  if (repo.language) lines.push(`| Primary language | ${repo.language} |`)
  lines.push(`| Stars | ${repo.stars.toLocaleString()} |`)
  lines.push(`| Forks | ${repo.forks.toLocaleString()} |`)
  if (repo.description) lines.push(`| Description | ${repo.description} |`)
  lines.push('')

  // Index stats
  lines.push('## Codebase Overview')
  lines.push('')
  lines.push(`- **Files indexed**: ${codeIndex.totalFiles.toLocaleString()}`)
  lines.push(`- **Total lines**: ${codeIndex.totalLines.toLocaleString()}`)
  if (analysis) {
    lines.push(`- **Detected framework**: ${analysis.detectedFramework ?? 'None'}`)
    lines.push(`- **Primary language**: ${analysis.primaryLanguage}`)
  }
  lines.push('')

  // Project summary section
  if (summary) {
    appendSummarySection(lines, summary)
  }

  // Issues section
  if (scanResults) {
    appendIssuesSection(lines, scanResults)
  }

  // Dependency graph highlights
  if (analysis) {
    appendDependencySection(lines, analysis)
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Issues-only Markdown
// ---------------------------------------------------------------------------

/**
 * Generate a Markdown report focused only on detected issues.
 */
export function exportIssuesToMarkdown(
  repo: GitHubRepo,
  scanResults: ScanResults,
): string {
  const lines: string[] = []
  lines.push(`# Issues Report — ${repo.fullName}`)
  lines.push('')
  lines.push(`> Scanned ${scanResults.scannedFiles} files on ${scanResults.scannedAt.toLocaleDateString()}`)
  lines.push('')
  const notice = coverageNotice(scanResults.repositoryCoverage)
  if (notice) lines.push(`> **Coverage notice:** ${notice}`, '')
  appendIssuesSection(lines, scanResults)
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Clipboard-friendly summary
// ---------------------------------------------------------------------------

/**
 * Generate a short Markdown snippet suitable for pasting into chat / email.
 */
export function exportSummaryClipboard(
  repo: GitHubRepo,
  codeIndex: CodeIndex,
  analysis: FullAnalysis | null,
  scanResults: ScanResults | null,
): string {
  const parts: string[] = []
  parts.push(`**${repo.fullName}** — ${repo.description ?? 'No description'}`)
  parts.push('')
  parts.push(`- ${codeIndex.totalFiles} files, ${codeIndex.totalLines.toLocaleString()} lines`)
  const notice = coverageNotice(codeIndex.coverage)
  if (notice) parts.push(`- ${notice}`)
  if (analysis) {
    parts.push(`- Framework: ${analysis.detectedFramework ?? 'N/A'}`)
    parts.push(`- Language: ${analysis.primaryLanguage}`)
    parts.push(`- Circular deps: ${analysis.graph.circular.length}`)
  }
  if (scanResults) {
    parts.push(`- Health: ${scanResults.healthGrade} (score: ${scanResults.healthScore})`)
    parts.push(`- Issues: ${scanResults.summary.critical} critical, ${scanResults.summary.warning} warning, ${scanResults.summary.info} info`)
  }
  return parts.join('\n')
}

// ---------------------------------------------------------------------------
// Section helpers
// ---------------------------------------------------------------------------

function appendSummarySection(lines: string[], summary: ProjectSummary): void {
  lines.push('## Project Summary')
  lines.push('')

  // Languages
  if (summary.languages.length > 0) {
    lines.push('### Languages')
    lines.push('')
    lines.push('| Language | Files | Lines | % |')
    lines.push('| --- | ---: | ---: | ---: |')
    for (const lang of summary.languages) {
      lines.push(`| ${capitalize(lang.lang)} | ${lang.files} | ${lang.lines.toLocaleString()} | ${lang.pct.toFixed(1)}% |`)
    }
    lines.push('')
  }

  // Key metrics
  lines.push('### Key Metrics')
  lines.push('')
  lines.push(`- **Module groups**: ${summary.clusterCount}`)
  lines.push(`- **Deepest chain**: ${summary.maxDepth}`)
  lines.push(`- **Circular dependencies**: ${summary.circularDeps.length}`)
  lines.push(`- **Unused files**: ${summary.orphanFiles.length}`)
  lines.push(`- **Entry points**: ${summary.entryPoints.length}`)
  lines.push('')

  // Top hubs
  if (summary.topHubs.length > 0) {
    lines.push('### Most-Imported Files')
    lines.push('')
    for (const hub of summary.topHubs.slice(0, 10)) {
      lines.push(`- \`${hub.path}\` — imported by ${hub.importerCount} files`)
    }
    lines.push('')
  }

  // External deps
  if (summary.externalDeps.length > 0) {
    lines.push('### External Dependencies')
    lines.push('')
    lines.push('| Package | Used by |')
    lines.push('| --- | ---: |')
    for (const dep of summary.externalDeps.slice(0, 20)) {
      lines.push(`| ${dep.pkg} | ${dep.usedByCount} files |`)
    }
    lines.push('')
  }

  // Health issues
  if (summary.healthIssues.length > 0) {
    lines.push('### Health Issues')
    lines.push('')
    for (const issue of summary.healthIssues) {
      lines.push(`- ⚠️ ${issue}`)
    }
    lines.push('')
  }
}

function appendIssuesSection(lines: string[], results: ScanResults): void {
  lines.push('## Issues')
  lines.push('')
  lines.push(`**Health grade**: ${results.healthGrade} (${results.healthScore}/100)`)
  lines.push('')
  lines.push(`| Severity | Count |`)
  lines.push(`| --- | ---: |`)
  lines.push(`| Critical | ${results.summary.critical} |`)
  lines.push(`| Warning | ${results.summary.warning} |`)
  lines.push(`| Info | ${results.summary.info} |`)
  lines.push(`| **Total** | **${results.summary.total}** |`)
  lines.push('')

  if (results.issues.length === 0) {
    lines.push('No issues detected.')
    lines.push('')
    return
  }

  // Group by severity
  const grouped = groupIssuesBySeverity(results.issues)

  for (const [severity, issues] of grouped) {
    lines.push(`### ${capitalize(severity)} (${issues.length})`)
    lines.push('')
    for (const issue of issues) {
      lines.push(`- **${issue.title}** — \`${issue.file}:${issue.line}\``)
      if (issue.suggestion) {
        lines.push(`  - 💡 ${issue.suggestion}`)
      }
    }
    lines.push('')
  }
}

function appendDependencySection(lines: string[], analysis: FullAnalysis): void {
  lines.push('## Dependency Analysis')
  lines.push('')
  lines.push(`- **Total files analyzed**: ${analysis.files.size}`)
  lines.push(`- **Entry points**: ${analysis.topology.entryPoints.length}`)
  lines.push(`- **Hub files**: ${analysis.topology.hubs.length}`)
  lines.push(`- **Orphan files**: ${analysis.topology.orphans.length}`)
  lines.push(`- **Max import depth**: ${analysis.topology.maxDepth}`)
  lines.push('')

  if (analysis.graph.circular.length > 0) {
    lines.push('### Circular Dependencies')
    lines.push('')
    for (const [a, b] of analysis.graph.circular.slice(0, 20)) {
      lines.push(`- \`${a}\` ↔ \`${b}\``)
    }
    if (analysis.graph.circular.length > 20) {
      lines.push(`- ... and ${analysis.graph.circular.length - 20} more`)
    }
    lines.push('')
  }
}

function groupIssuesBySeverity(issues: CodeIssue[]): Map<string, CodeIssue[]> {
  const order = ['critical', 'warning', 'info'] as const
  const map = new Map<string, CodeIssue[]>()
  for (const s of order) {
    const filtered = issues.filter(i => i.severity === s)
    if (filtered.length > 0) map.set(s, filtered)
  }
  return map
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}
